server:
  port: 8000
spring:
  profiles:
    # 激活对应的命名空间
    active: dev
  application:
    name: service-order
  cloud:
    nacos:
        server-addr: 127.0.0.1:8848
        config:
          import-check:
            enabled: false
          # 激活对应的命名空间，默认为public
          namespace: ${spring.profiles.active:public}

# 依据环境设置相应配置
## namespace-dev
---
spring:
  config:
    import:
      # 配置好group
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev

## namespace-test
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:haha.properties?group=order
    activate:
      on-profile: test

## namespace-prod
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:hehe.properties?group=order
    activate:
      on-profile: prod